### ISSUE TITLE
add VNC-enabled image

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renkulab-docker#1]
We have recently developed images that allow using a desktop via the browser for e.g. image processing applications. We should add the image build to our standard collection of base images here.

**Comment by rokroskar** [comment]
@erbou any chance we could add this? see also #5 it will affect the VNC image build.

**Comment by erbou** [comment]
The installations requires license files and file installation keys that cannot be shared. We can create a template for building the image from a configuration file.

**Comment by rokroskar** [comment]
Yes of course, we can have the base image prepared and all the user has to do is add those in to their own Dockerfile

**Comment by emmjab** [comment]
Do we still want to add this to the available images? Is it this? https://github.com/SwissDataScienceCenter/renku-jupyterlab-vnc ? 
@erbou @rokroskar

**Comment by rokroskar** [comment]
afaik we don't currently have any users that require it.

**Comment by rokroskar** [comment]
marking as `wont fix` for now - we have had no requests for this since the issue has been opened. If requests resurface at some point we can revisit this.
