### ISSUE TITLE
Working directory is not set to root when creating a notebook

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renkulab-docker#101]
## Description

In the interactive env, if we go to a sub-folder and then create a notebook, the working directory of the notebook is not set to the root of the home directory (i.e. `/work/<project>`). It would be less confusing if the working directory of the notebooks is always set to the home directory.

## Reproduce

1. Start an interactive env
2. On the file explorer and go to a sub-folder (e.g. `data`)
3. Create a new notebook
4. Running `%pwd` in the notebook shows `/work/<project>/data` as the current directory.

**Comment by rokroskar** [comment]
I don't think there is much for us to do here, since that's JupyterLab behavior.
