### ISSUE TITLE
Indicate to the user that changes are not pushed to the remote

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renkulab-docker#102]
When committing in a running notebook, it'd be nice if there was an indication that changes were committed inside the notebook, but not pushed to the remote, similar to the `This branch is 1 commit ahead of origin/master` message you get in the git commandline. This helps prevent dataloss and makes it more obvious to a user that pushing might be necessary.

**Comment by rokroskar** [comment]
We do this in a few different places now - the commandline prompt shows it, and the status of the session in the UI indicates whether the git status is out of sync with the remote.
