### ISSUE TITLE
Improve installing of jupyterlab extensions

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renkulab-docker#109]
There's many really neat jupyterlab extensions that allow notebooks to do awesome stuff, but setting them up in renku is not very user-friendly at the moment.

Most of the extension have some documentation as in https://ipyleaflet.readthedocs.io/en/latest/installation.html#jupyterlab-extension that instruct you to run a command like `jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-leaflet`

There are several issues with this:
- Running these kinds of commands fails with a Webpack error on renkulab, with no way for the user to know what to do instead
- Even if the command worked, it would have to be re-executed every time the image is started/rebuilt
- We don't have any docs on how to properly install extensions on renkulab

There's also an experimental Widget manager in jupyterlab that a user can enable in the settings dropdown, which works for installing extensions, but also has the problem of not persisting the changes through image builds.

The way to properly install an extension on renkulab is to add the `jupyter labextension install` command in the `Dockerfile`

Ideally, we'd:
- Add docs on how to install extensions, detailing that they should be added to the Dockerfile
- Show some sort of warning (popup or in the terminal?) if a user runs a `jupyter labextension install` command with a link to those docs
- Show some warning in the Widget Manager ui that also points to the docs (Or not show the option for the widget manager in the menu)
- (Optionally) figure out why the `jupyter labextension install` command fails and fix it? But since we don't want users to install this way anyways, maybe that's not something we want.

**Comment by rokroskar** [comment]
I'm not 100% sure this issue is still relevant - afaik most extensions with the new version of JupyterLab can just be installed via `pip`. In which case it's as simple as adding them to the `requirements.txt` file.

**Comment by rokroskar** [comment]
afaik this isn't an issue anymore for most extensions.
