### ISSUE TITLE
VNC terminal the powerline prompt is missing some fonts

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renkulab-docker#144]
In the VNC image, the powerline prompt is missing some fonts:

![image](https://user-images.githubusercontent.com/3353586/113718480-f8781680-96ec-11eb-82c0-38e5a6299958.png)

should be:

![image](https://user-images.githubusercontent.com/3353586/113718505-02017e80-96ed-11eb-8a34-206c442d6788.png)

_Originally posted by @rokroskar in https://github.com/SwissDataScienceCenter/renkulab-docker/issues/143#issuecomment-814121502_

**Comment by gavin-k-lee** [comment]
![image](https://user-images.githubusercontent.com/22785147/113881835-14e38400-97bd-11eb-81d5-7a0c6a81688e.png)

After a day of googling and failing - turns out the easiest thing to do is to get some fonts and use the gnome terminal: `apt-get install ttf-dejavu gnome-terminal` - the issue seems to be with powerline and uxterm/xterm.

**Comment by rokroskar** [comment]
Oh great! The gnome terminal will be nicer anyway. i wonder if it works with the gnome terminal _without_ installing fonts?

**Comment by gavin-k-lee** [comment]
No it doesn't - I tried that though
