### ISSUE TITLE
RStudio version is out of date

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renkulab-docker#154]
- The current RStudio version is pinned at 1.2.5042 but the latest is 1.4.
https://github.com/SwissDataScienceCenter/renkulab-docker/blob/7df1a7204497439b1c934248804fdacad94ab1b5/docker/r/Dockerfile#L33

- There are a few nice upgrades, for example using renv instead of packrat as the default package manager.
- The fix would need testing.

**Comment by gavin-k-lee** [comment]
There does not yet seem to be a reliable fix - but it is a (well) known issue now: see
https://github.com/2i2c-org/external/issues/12

**Comment by TaoSunVoyage** [comment]
> If you want to use RStudio 1.4.x, you need to set the RSESSION_PROXY_RSTUDIO_1_4 environment variable. This adds additional parameters to the execution of server.

https://github.com/jupyterhub/jupyter-rsession-proxy

**Comment by TaoSunVoyage** [comment]
there is soon going to be a release of `jupyter-rsession-proxy` to fix the issue with RStudio1.4, see jupyterhub/jupyter-rsession-proxy#97 and jupyterhub/jupyter-rsession-proxy#107
