### ISSUE TITLE
Outdated CRAN snapshot?

### ISSUE THREAD

**Issue by lorenzwalthert** [SwissDataScienceCenter/renkulab-docker#163]
Not sure this belongs to this repo, feel free to transfer 😀. When I start an RStudio instance with R 4.04 in renku, I get

![Screenshot 2021-05-28 at 17 11 22](https://user-images.githubusercontent.com/10477073/120005602-48ca7100-bfd8-11eb-9065-424b4fcf8dc4.png)

With my limited docker knowledge, I figured this was strange given that (apparently) the base image used was `rocker/verse:4.0.4` and by default, the CRAN snapshot for this should correspond to the latest day that version was the lastest R version and that's [not 2020](https://cran.r-project.org/bin/windows/base/old/).

Thanks a lot for this cool project.

**Comment by gavin-k-lee** [comment]
Hi Lorenz,

I spun up a new R project with the latest Docker image tag: `renku/renkulab-r:4.0.4-0.7.6` and when I ran that I got this: 
![image](https://user-images.githubusercontent.com/22785147/120215476-0f8f3c80-c236-11eb-9bbb-693793886558.png)

which seems slightly newer than the one you got.

Can you link to the specific project from which you got that? Perhaps the Docker image used is not the same one.

**Comment by lorenzwalthert** [comment]
`2021-03-30` is much better, not just slightly 😀. Here is the repo: https://renkulab.io/gitlab/lorenz.walthert/test-project

**Comment by gavin-k-lee** [comment]
Great. Yes it seems like your project was slightly outdated. If you change the Docker image tag to 0.7.6 you should get the 2021-03-30 version.

Check out my fork of your project: https://renkulab.io/projects/lee.gavin.k/test-project/environments to see that.

The line you need to change is https://renkulab.io/gitlab/lorenz.walthert/test-project/-/blob/master/Dockerfile#L3

**Comment by lorenzwalthert** [comment]
Thanks. I see your solution (which would work for me). However, I created that project last week and I just created another and the problem exists there too. Is the template outdated? I.e. on project creation, it seems as `renku/renkulab-r:4.0.4-0.7.5` is selected as of today. Is that intentional?

**Comment by gavin-k-lee** [comment]
Yes unfortunately the template is outdated https://github.com/SwissDataScienceCenter/renku-project-template/blob/master/R-minimal/Dockerfile I will put in an issue to update this ASAP.
