### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renkulab-docker#171]
@ableuler suggested that we should somehow test that all images work properly and can not only launch but also provide a functional UI. I do not think we currently do this anywhere across all images since if I am not mistaken the renku acceptance tests only focus on a single image - not all the image that are built with this repo.

With the addition of amalthea doing these tests becomes a bit easier because we can now launch a session by just installing amalthea - without deploying all of renku. However, I believe that this is something that we should be doing regardless of using amalthea or not.

So I propose the following steps to add tests:
- **Add a github action** here that would install amalthea and launch a simple session (i.e. no oidc) with every image in the repo and confirm that all k8s components for the session are running and are healthy. We have already implemented tests like this for [amalthea itself](https://github.com/SwissDataScienceCenter/amalthea/pull/39) so doing that here will be easy. And I think it is better to add the tests here rather than expand the amalthea tests because having such tests here would allow us to catch any issues the quickest. If the tests were in amalthea then a change in any image that causes a problem would be caught only when something in amalthea changes - which should not happen that often. Another option is to actually add the tests across all images in both places - the amalthea repo and here. Then a change that causes problems from any side will be caught immediately.
- **Add minimal UI testing** to ensure that the sessions with all images not only launch successfully but are also usable in the browser. This is a tougher thing to do. My feeling is that we should try to avoid adding more stuff to the acceptance tests on renku and just do something within this repo. I have never used [cypress.io](https://docs.cypress.io/guides/getting-started/writing-your-first-test#Add-a-test-file) but it looks very promising to me for doing this. And cypress also publishes ready-to-use docker images we could use. So the UI test would involve a github action that launches a kind cluster, installs amalthea, launches a pod in the cluster with cypress and runs the tests across all images. Cypress can also run tests across multiple browsers but so far only supports chrome-family browsers and firefox.

@rokroskar @gavin-k-lee what do you think?

**Comment by rokroskar** [comment]
@olevski this has been done, no?

**Comment by rokroskar** [comment]
tests are already there - we can talk about improving them separately imho. closing this for now.
