### ISSUE TITLE
Make `start-notebook.sh` the default command in all base images

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renkulab-docker#192]
We currently use `start-singleserver.sh` as default command which doesn't work outside of a Jupyterhub context. Using `start-notebook.sh` - which is actually the default from jupyter docker stack images - will enable us to not overwrite the command when launching a session in the future.

**Comment by rokroskar** [comment]
should we call it something more generic? Like `start-session.sh` and define where it needs to go? Then it's not notebook-specific and can be sensibly applied to any other type of server.

**Comment by ableuler** [comment]
Yeah, I think we've moved on quite a bit since this issue was created. For me it's a two stage process: 

1. We still have to set the command at the k8s level because images which have the JH specific command set as entrypoint are still out there and in use. Currently we're actually setting `jupyter lab` as command and not initially assumed `start-notebook.sh`.

2. Images with JH specific entrypoint are not supported anymore and we can thus stop setting the command on k8s all together and just run whatever command the image specifies.

I think we're close to the end of phase 1 and I would hope that we can soon close this issue.

**Comment by rokroskar** [comment]
this has been changed to `jupyter server` to keep it more generic.
