### ISSUE TITLE
Find a solution to VSCode extension bug

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renkulab-docker#195]
A user reported the VSCode extension giving a bug: "500 Internal Server Error" - it complains that the `~/.local/bin` folder does not exist in the https://github.com/SwissDataScienceCenter/renkulab-docker/blob/master/scripts/install-vscode.sh script. 

@TaoSunVoyage found a quick bug fix: https://renkulab.io/gitlab/tao.sun/metadata-auto/-/blob/class_apis/Dockerfile.

The problem seems to do with environment variables and running things from bash rather than inside the Dockerfile.

**Acceptance Criteria**
- Alter the `install-vscode.sh` script to fix the issue; or
- Alter the instructions for adding the extension on Discourse;

**Comment by rokroskar** [comment]
addressed in #205 - will make a comment on Discourse after a release has been made
