### ISSUE TITLE
Publish images with latest tag for every official/proper release

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renkulab-docker#200]
These are not urgently necessary but are really nice to have.

For example one obvious usage is that the fallback image in the notebook service can be renku/renkulab-py:latest.

Rather than a specific tagged one.

**Comment by rokroskar** [comment]
see also #201

**Comment by rokroskar** [comment]
This is already the case for merges to master, which I think is the correct behavior (rather than on tag). wdyt?

**Comment by rokroskar** [comment]
This is already done.
