### ISSUE TITLE
Add notebook resource usage extension

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renkulab-docker#33]
Install https://github.com/yuvipanda/nbresuse in the base image.

**Comment by emmjab** [comment]
I think this is a good feature for warning users of memory usage, part of an epic we should make surrounding large-ish data usage.

Tested here: https://renkulab.io/projects/emma.jablonski/penguins & commit: fd967254

(check the bottom left of the jupyterlab notebook to see the memory, or in the tree view of a notebook at the top right)

Do we have a memory limit to enforce? @pameladelgado (also useful for QA)/ @rokroskar

**Comment by rokroskar** [comment]
Make a PR! :) 💯
