### ISSUE TITLE
Error for renku==2.9.2

### ISSUE THREAD

**Issue by guiwitz** [SwissDataScienceCenter/renkulab-docker#442]
**Describe the bug**
Building a new Python project on renkulab currently fails. It seems that it's an issue with a missing renku version:
```
#8 25.92 ERROR: No matching distribution found for renku==2.9.2
```

**Link to project**
https://gitlab.renkulab.io/guillaume.witz1/davpy-demos/-/jobs/701721

**To Reproduce**
Just create a default project.

**Run environment (please complete the following information):**
 - Default python project on renkulab

**Comment by guiwitz** [comment]
There's apparently a discrepancy between the latest release on Github 2.9.2 and the latest stable on PyPi which is 2.9.1 On PyPi there are only release candidates for 2.9.2.

**Comment by rokroskar** [comment]
sorry we missed this @guiwitz - I believe you managed to try a new project right when the new renku version was being released. Should work fine now so I'll close this for the time being.
