### ISSUE TITLE
include R versions in travis build matrix

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renkulab-docker#49]
#48 builds the renku R image based on rocker/rstudio. This should allow us to easily support base images with different versions of R - we should modify the travis build to include various R versions.

**Comment by emmjab** [comment]
this was done at some point and was also included in the move to github actions #72

**Comment by emmjab** [comment]
Whoops, didn't realize this actually refers to the version of R specified in the image. Can still add this to the matrix.

**Comment by rokroskar** [comment]
Might be easier with a "build R images" workflow rather than the generic one?

**Comment by emmjab** [comment]
closed by #95
