### ISSUE TITLE
Fix symbolic link from home directory to repo

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renkulab-docker#68]
When launching a shell in an interactive session, the user is dropped into the checked-out repo at `/work/<repo-name>/`. The users home directory `/home/jovyan` contains a `work` folder which is empty. I assume that this work folder is supposed to be a symbolic link to `/work`, but it is not. 

Alternatively, one could create a symbolic link directly to the repo, `/home/jovyan/<repo-name> --> /work/<repo-name>`.

**Comment by emmjab** [comment]
The R images also have a similar issue, in addition to including the files from the project in the parent directory of the repo (not sure which change introduced this bug

**Comment by rokroskar** [comment]
> The R images also have a similar issue, in addition to including the files from the project in the parent directory of the repo (not sure which change introduced this bug

@emmjab could you please clarify?

**Comment by emmjab** [comment]
> @emmjab could you please clarify?

Huh, just checked the latest R image and one from as early as end of March and neither have this problem.

There used to be this situation where `/work` and `/work/project-name` both had copies of the project's files. Guess it went away!
