### ISSUE TITLE
enable running of custom setup scripts at launch time

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renkulab-docker#73]
In some cases it makes sense to want to have some custom script that executes when the container is started. One use-case is to `pip install -e` install a package that is developed in the project itself (it's hard to do this otherwise because the repo itself is only mounted at runtime). 

The suggestion is to have some convention for this script name like `runtime-init.sh` or something similar. 

cc @nperraud

**Comment by erbou** [comment]
Another example of use cases is to prepare an environment that is user-specific and cannot be generalized to all users for the project - e.g. create site xml files required by certain packages that contain user specific attributes, such as usernames.

In that case it would make sense to let users (or groups) add custom attributes to their profiles, which can be injected in the scripts at start time.

**Comment by rokroskar** [comment]
This has been addressed by using a `post-init.sh` script, but probably isn't documented well enough yet. I will open a new issue about that.
