### ISSUE TITLE
An image that supports VSCode

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renkulab-docker#83]
Instead of JupyterLab as the UI, it might be nice to also offer VSCode as an alternative

Either within the browser:

- https://github.com/cdr/code-server

Or as a VSCode Remote Server:

- https://code.visualstudio.com/docs/remote/ssh

**Comment by rokroskar** [comment]
There is https://github.com/betatim/vscode-binder - I think I have a project somewhere on dev that ports this over to one of our base images.

**Comment by rokroskar** [comment]
Oh, there is also this: https://medium.com/@fingr8/bring-vs-code-to-your-jupyterlab-187e59dd1c1b

**Comment by rokroskar** [comment]
Oh I remember now where I got stuck! It works, but I couldn't execute notebooks from vscode running as a jupyter server extension. I'll dig up the project once dev is back online - I think it's a matter of figuring out some parameters in vscode for starting jupyter servers and then it's basically good to go.
