### ISSUE TITLE
Inject group preferences in a project

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renkulab-docker#86]
This is an extension of issue #65.

I have a project containing a notebook that uses a licensed software, which is going to be forked and run by a large group of people (e.g. 100 students).

I obviously cannot copy the software license in a public project's repo. I also want to allow other users who are not entitled to use my license to seamlessly (i.e. fork, start env, and play) run my project with their own license, if they have one.

Note: the above is used as an example. We could think of other use cases, such as seamlessly deploying core-site.xml and other configs to a project that needs to access a hadoop cluster backend.

We can assume that the project uses a stock docker image, and that it is possible to agree on a standard configuration scheme for that image, such as an agreed-upon environment variable containing a license key.

At the moment I can think of two options if I exclude all other options that involve copying the license in the project's repo:

1. Configure each personal (private) `renku-env` as described in #65. This option provides a seamless experience, however users must set their environment themselves, and must remember to update it when the license changes.

2. Extend #65 to support the concept of shared properties, e.g.  a group-owned `renku-env` repos, that can be added as submodules or hooks in the user's `renku-env` repos. When a user creates her personal environment, a list of shared properties can be suggested to her (e.g. the `renku-env` of all the groups that she is member of). In addition we could tag the groups, e.g. `default`, which are automatically applied to members of the group who don't have an environment. We have to be careful with that thought - if we allow someone to create a default for someone else, the feature could easily be abused.

As a user my preference lean on .2, because it allows me to easily manage the properties of a large number of non-expert users. I can for instance create a repo with a matlab license, and deploy the license to a 100 students by making them all members of that repo.

**Comment by rokroskar** [comment]
If it's for the group, why not bake it into the docker image?

**Comment by erbou** [comment]
I exclude all other options that involve baking the license in the image, because I may have many different projects using the software, and many team members working on their own copies of the projects. That's a lot of projects that I need to keep up to date when the license or configuration properties changes. More importantly, I would like to be able to share the project as-is with my collaborators, who may have their own license (think matlab). I cannot share the license, and I also don't want the license to be part of the commit, so that we have the same versions of the code/docker image when comparing our results. The feature introduced in #65 makes it easier, because we just need to maintain the user profiles, instead of 100s of projects. I am just suggesting to go one step further, and manage common properties from a single location.

**Comment by rokroskar** [comment]
What happens when a user is a member of multiple groups that each set their own group-level properties? How should we decide at runtime which one to apply?

**Comment by rokroskar** [comment]
closing as this will no longer be relevant when gitlab is not the source of group membership.
