### ISSUE TITLE
Include jupyterlab toc (table of content) in default image

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renkulab-docker#87]
A participant of our carving through data course suggested to use the [jupyterlab navbar](https://github.com/shoval/jupyter-navbar) to make larger notebooks easier to navigate. It looks promising, we might want to include this in our standard python image.

**Comment by rokroskar** [comment]
Last commit was in July 2019... don't think we want it in the standard image? But maybe provide docs of useful extensions?

**Comment by ableuler** [comment]
Indeed, the originally suggested add on does not support jupyterlab and seems to be unmaintained. However [this jupyterlab extension](https://github.com/jupyterlab/jupyterlab-toc) provides the same functionality and works like a charm! It's quite powerful and it definitely makes any notebook in which you have to scroll much easier to handle (see screenshot).
![image](https://user-images.githubusercontent.com/13014091/76873443-110d5880-686e-11ea-883d-f3cd1586841f.png)

It increased the image size by ~80 MB though. What do you think?

**Comment by nperraud** [comment]
For CTD, it is a now brainer...

**Comment by rokroskar** [comment]
Sure this one seems good! Would be happy to get a PR with this change!
