### ISSUE TITLE
add an extension to jupyterlab for "back to renkulab"

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renkulab-docker#97]
**Problem**
It has always been annoying to find the renkulab tab with the project open from the notebook that is running the project, especially when:
* you might have closed the tab with renkulab
* you might have multiple notebooks running
* you might have many unorganized tabs open

Since we also have awesome new functionality to run anonymous sessions, it's even more possible that users will have trouble connecting back to renkulab.

**Solution**
Let's try making a Jupyter extension (and if this is successful, and RStudio extension), for sending users back to renkulab.

Open questions:
- should this be implemented as some kind of UI wrapper around Jupyterlab instead of a Jupyterlab extension? (iframes? maaaaybe not)
- where should the extension take you (and where **can** the extension take you, e.g. what information from renkulab is still available when you're in a notebook)? environments page for the user, environments page for the project, project overview page, ...gitlab?)
- is this repo a good place for this?

**Comment by rokroskar** [comment]
I believe this is no-longer an issue with the iframe
